/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.trungly.friendfeed;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blogger=0x7f020000;
        public static final int comment=0x7f020001;
        public static final int comment_friend=0x7f020002;
        public static final int delicious=0x7f020003;
        public static final int facebook=0x7f020004;
        public static final int feed=0x7f020005;
        public static final int ff=0x7f020006;
        public static final int flickr=0x7f020007;
        public static final int goodreads=0x7f020008;
        public static final int googlereader=0x7f020009;
        public static final int icon=0x7f02000a;
        public static final int netflix=0x7f02000b;
        public static final int picasa=0x7f02000c;
        public static final int twitter=0x7f02000d;
        public static final int youtube=0x7f02000e;
    }
    public static final class id {
        public static final int body=0x7f050007;
        public static final int bottom_bar=0x7f050009;
        public static final int comment_body=0x7f050002;
        public static final int comment_icon=0x7f050001;
        public static final int comment_item=0x7f050000;
        public static final int entry_item=0x7f050003;
        public static final int footer=0x7f050008;
        public static final int header=0x7f050004;
        public static final int header_text=0x7f050006;
        public static final int main_window=0x7f05000a;
        public static final int refresh_button=0x7f05000b;
        public static final int service_icon=0x7f050005;
    }
    public static final class layout {
        public static final int comment_item=0x7f030000;
        public static final int entry_item=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
